EQueueVidly/ViewModels/TeacherViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EQueueVidly.ViewModels
{
    public class TeacherViewModel
    {
        public string TeacherId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

EQueueVidly/Controllers/Api/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using AutoMapper;
using EQueueVidly.Models;
using EQueueVidly.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace EQueueVidly.Controllers.Api
{
    public class TeachersController : ApiController
    {
        private ApplicationDbContext _context;

        public TeachersController()
        {
            _context = new ApplicationDbContext();
        }

        public IHttpActionResult GetTeachers()
        {
            var workQuery = GetApplicationUsersInRole("Teacher").ToList();

            var customerDtos = workQuery
                .ToList()
                .Select(Mapper.Map<ApplicationUser, TeacherViewModel>);
            return Ok(customerDtos);
        }
        [Route("api/resources")]
        public IHttpActionResult GetResources()
        {
            var resourceData = new List<ScheduleResource>();


            var teachers = GetApplicationUsersInRole("Teacher").ToList();


            foreach (var teacher in teachers)
            {
                var teacherRes = new ScheduleResource();
                teacherRes.id = teacher.Id;
                teacherRes.title = teacher.FirstName+" "+teacher.LastName;
                resourceData.Add(teacherRes);
            }


            return Json(resourceData);
        }

        public IEnumerable<ApplicationUser> GetApplicationUsersInRole(string roleName)
        {
            return from role in _context.Roles
                where role.Name == roleName
                from userRoles in role.Users
                join user in _context.Users
                on userRoles.UserId equals user.Id
                select user;
        }

       /* public IEnumerable<ApplicationUser> GetUserQueue(string userId)
        {
            
                var works = _context.Appointments;
                var queueItems = _context.Attendees.Where(q => q.UserId == userId);
                var users = _context.Users;

            var result = from q in queueItems
                         join w in works on q.WorkTimeId equals w.Id
                         join u in users on w.User_Id equals u.Id
                            select new
                            {
                                FirstName = u.FirstName,
                                LastName = u.LastName,
                                /*EndTime = q.EndTime,
                                StartTime = q.StartTime,
                                WorkDate = w.AppointmentDate#1#
                            };
            return null;

        }*/
    }
}

EQueueVidly/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using DHTMLX.Common;
using DHTMLX.Scheduler;
using DHTMLX.Scheduler.Controls;
using DHTMLX.Scheduler.Data;
using EQueueVidly.Domain;
using EQueueVidly.Dtos;
using EQueueVidly.Models;
using EQueueVidly.ViewModels;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace EQueueVidly.Controllers
{
    [Authorize]
    public class AppointmentsController : BaseController
    {
#region create
        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public JsonResult SaveAppointment(ScheduleEvent appointment)
        {
            var teacher = unitOfWork.Teachers.GetTeacherByAccountId(User.Identity.GetUserId());
            var schEvent = new Appointment();
            schEvent.StartDate = DateTime.Parse(appointment.start);
            schEvent.EndDate = DateTime.Parse(appointment.end);
            schEvent.Durration = appointment.duration;
            schEvent.TimeLimit = appointment.timeLimit;
            schEvent.Title = appointment.title;
            schEvent.TeacherId = teacher.Id;
            schEvent.Capacity = (int)appointment.duration / appointment.timeLimit;
            schEvent.CreationDate = DateTime.Today;
            try
            {
                unitOfWork.Appointments.Add(schEvent);
                unitOfWork.Complete();
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet); ;
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
#endregion
#region read
        public JsonResult GetAppointments(string start, string end)
        {
            var teacher = unitOfWork.Teachers.GetTeacherByAccountId(User.Identity.GetUserId());
            DateTime Start = DateTime.Parse(start);
            DateTime End = DateTime.Parse(end);
            List<ScheduleEvent> EventItems = new List<ScheduleEvent>();
            IEnumerable<Appointment> appointments = null;
            appointments = unitOfWork.Teachers.GetAllAppointments(Start, End, teacher.Id).ToList();
            foreach (var scheduleEvent in appointments)
            {
                var temp = DateTime.Compare(scheduleEvent.StartDate, DateTime.Now);
                ScheduleEvent itm = new ScheduleEvent();
                itm.id = scheduleEvent.Id.ToString();
                itm.title = scheduleEvent.Title;
                itm.start = scheduleEvent.StartDate.ToString("s");
                itm.end = scheduleEvent.EndDate.ToString("s");
                itm.duration = scheduleEvent.Durration;
                itm.timeLimit = scheduleEvent.TimeLimit;
                itm.TeacherId = scheduleEvent.TeacherId;
                itm.TeacherName = scheduleEvent.Teacher.account.FirstName + scheduleEvent.Teacher.account.LastName;
                itm.capacity = scheduleEvent.Capacity;
                itm.queueIiems = scheduleEvent.Attendees.Count;
                itm.color = temp <= 0 ? "#D32F2F" : "#7B1FA2";
                EventItems.Add(itm);
            }
            return Json(EventItems, JsonRequestBehavior.AllowGet);
        }

        //returns events to student
        public JsonResult GetAppointmentsForTeacher(string start, string end, int Id)
        {
            var student = unitOfWork.Students.GetStudentByAccountId(User.Identity.GetUserId());
            var teacher = unitOfWork.Teachers.GetTeacherById(Id);
            IQueryable<Attendee> currentUserAppointments=null;
            if (student != null)
            {
                 currentUserAppointments = unitOfWork.Attendees.GetAttendeesByStudentId(student.Id);
            }
            DateTime Start = DateTime.Parse(start);
            DateTime End = DateTime.Parse(end);
            List<ScheduleEvent> EventItems = new List<ScheduleEvent>();
            IEnumerable<Appointment> appointments = null;
            appointments = unitOfWork.Teachers.GetAllAppointments(Start, End, Id).ToList();
            foreach (var scheduleEvent in appointments)
            {
                var temp = DateTime.Compare(scheduleEvent.StartDate, DateTime.Now);
                ScheduleEvent itm = new ScheduleEvent();
                itm.id = scheduleEvent.Id.ToString();
                itm.title = scheduleEvent.Title;
                itm.start = scheduleEvent.StartDate.ToString("s");
                itm.end = scheduleEvent.EndDate.ToString("s");
                itm.duration = scheduleEvent.Durration;
                itm.timeLimit = scheduleEvent.TimeLimit;
                itm.TeacherId = scheduleEvent.TeacherId;
                itm.TeacherName = teacher.account.FirstName +" "+ teacher.account.LastName;
                itm.capacity = scheduleEvent.Capacity;
                itm.queueIiems = scheduleEvent.Attendees.Count;
                if (currentUserAppointments != null)
                {
                    foreach (var userAppointment in currentUserAppointments)
                    {
                        if (userAppointment.AppointmentId == scheduleEvent.Id)
                        {
                            itm.imageurl = "Content/images/ready.png";
                        }
                    }
                }
                itm.color = temp <= 0 ? "#D32F2F" : "#7B1FA2";
                EventItems.Add(itm);
            }
            return Json(EventItems, JsonRequestBehavior.AllowGet);
        }

        public ViewResult Details(int id)
        {
            var Appointment =  unitOfWork.Appointments.GetAppointmentById(id);

            if (Appointment == null)
            {
                return null;
            }

            var model = new AppointmentDetailsViewModel();
            model.Title = Appointment.Title;
            model.StartDate = Appointment.StartDate;
            model.EndDate = Appointment.EndDate;
            model.Capacity = Appointment.Capacity;
            model.TimeLimit = Appointment.TimeLimit;

            foreach (var attendee in Appointment.Attendees)
            {
                var item = unitOfWork.Attendees.GetAttendeesById(attendee.Id);
                model.Attendees.Add(new AttendeeViewModel
                {
                    FullName = item.Student.Account.FirstName + " " + item.Student.Account.LastName,
                    Start = item.Start,
                    End = item.End
                });
            }
            return View(model);
        }

        #endregion#
#region update
[Authorize(Roles = "Teacher")]
[HttpPost]
public JsonResult EditAppointment(ScheduleEvent appointment)
{
    var teacher = unitOfWork.Teachers.GetTeacherByAccountId(User.Identity.GetUserId());
    var app_id = Int32.Parse(appointment.id);
    var schEvent = unitOfWork.Appointments.Find(a => a.Id == app_id).FirstOrDefault();
    if (schEvent == null)
    {
        return Json(false, JsonRequestBehavior.AllowGet); ;
    }
    schEvent.StartDate = DateTime.Parse(appointment.start);
    schEvent.EndDate = DateTime.Parse(appointment.end);
    schEvent.Durration = appointment.duration;
    schEvent.TimeLimit = appointment.timeLimit;
    schEvent.Title = appointment.title;
    schEvent.TeacherId = teacher.Id;
    schEvent.Capacity = (int) appointment.duration/appointment.timeLimit;
    try
    {
        unitOfWork.Appointments.Update(schEvent);
        unitOfWork.Complete();
    }
    catch (Exception)
    {
        return Json(false, JsonRequestBehavior.AllowGet); ;
    }
    return Json(true, JsonRequestBehavior.AllowGet); ;
}
#endregion
#region delete
[Authorize(Roles = "Teacher")]
public bool DeleteAppointment(int AppointmentId)
{
    try
    {
        var appointment = unitOfWork.Appointments.Find(a => a.Id == AppointmentId).FirstOrDefault();
        unitOfWork.Appointments.Remove(appointment);
        unitOfWork.Complete();
    }
    catch (Exception)
    {
        return false;
    }
    return true;

}
#endregion

    }
}

EQueueVidly/Controllers/AttendeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EQueueVidly.Models;
using EQueueVidly.ViewModels;
using Microsoft.AspNet.Identity;

namespace EQueueVidly.Controllers
{
    public class AttendeesController : BaseController
    {
        #region creat
        [Authorize(Roles = "Student")]
        [HttpGet]
        public JsonResult JoinEvent(int AppointmentId)
        {
            var appointment = unitOfWork.Appointments.GetAppointmentById(AppointmentId);
            var userId = User.Identity.GetUserId();
            var student = unitOfWork.Students.Find(s => s.AccountId == userId).FirstOrDefault();

            if (appointment != null && student != null)
            {
                int minutes = appointment.TimeLimit * (appointment.Attendees.Count);
                int span = appointment.TimeLimit * (appointment.Attendees.Count + 1);
                Attendee queueItem = new Attendee
                {
                    StudentId = student.Id/*User.Identity.GetUserId()*/,
                    JoinDate = DateTime.Now,
                    AppointmentId = AppointmentId,
                    Start = appointment.StartDate.AddMinutes(minutes),
                    End = appointment.StartDate.AddMinutes(span)
                };


                try
                {
                    unitOfWork.Attendees.Add(queueItem);
                    unitOfWork.Complete();
                }
                catch (System.Data.Entity.Infrastructure.DbUpdateException ex)
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }

                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region read

        public ActionResult GetStudentEvents(string start, string end)
        {
            var student = unitOfWork.Students.GetStudentByAccountId(User.Identity.GetUserId());
            DateTime Start = DateTime.Parse(start);
            DateTime End = DateTime.Parse(end);
            var events = unitOfWork.Attendees.GetAttendeesByTimeSpan(Start, End, student.Id).ToList();
            List<StudentEvent> EventItems = new List<StudentEvent>();
            foreach (var queueItem in events)
            {
                StudentEvent studentEvent = new StudentEvent()
                {
                    id = queueItem.Id,
                    start = queueItem.Start.ToString("s"),
                    end = queueItem.End.ToString("s"),
                    TeacherName = queueItem.Appointment.Teacher.account.FirstName + " " + queueItem.Appointment.Teacher.account.LastName,
                    title = queueItem.Appointment.Title
                };
                EventItems.Add(studentEvent);
            }
            return Json(EventItems, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public bool IsAppointmentMember(string userId, int eventId)
        {
            var student = unitOfWork.Students.Find(s => s.AccountId == userId).FirstOrDefault();
            var items = unitOfWork.Attendees.Find(q => (q.StudentId == student.Id && q.AppointmentId == eventId)).ToList();
            if (items.Count != 0)
            {
                return true;
            }
            return false;
        }

        public ActionResult QrCode(int id)
        {
           var appointment = unitOfWork.Attendees.GetAttendeesById(id);
            var user_id = User.Identity.GetUserId();
           var user = context.Users.Find(user_id);
            QrCodeViewModel viewModel = new QrCodeViewModel()
            {
                StudentName = user.FirstName + " " +user.LastName,
                Start = appointment.Start.ToString("g"),
                End = appointment.End.ToString("g")
            };
           
           return View(viewModel);
        }
        #endregion
        #region update
        #endregion
        #region delete
        public bool DeleteEvent(int AttendeeId)//todo replase queue items after deleting
        {
            try
            {
                var attendee = unitOfWork.Attendees.GetAttendeesById(AttendeeId);
                var attendees = attendee.Appointment.Attendees.OrderByDescending(a=>a.Start);
                foreach (var item in attendees)
                {
                    if (item.Start > attendee.Start)
                    {
                        var subtr = 0 - attendee.Appointment.TimeLimit;
                        item.Start = item.Start.AddMinutes(subtr);
                        item.End = item.End.AddMinutes(subtr);
                        unitOfWork.Attendees.Update(item);
                        unitOfWork.Complete();
                    }
                }
                unitOfWork.Attendees.Remove(attendee);
                unitOfWork.Complete();
            }
            catch (Exception)
            {
                return false;
            }
            return true;

        }
        #endregion
    }
}

EQueueVidly/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using EQueueVidly.Domain;
using EQueueVidly.Models;
using EQueueVidly.ViewModels;
using Microsoft.AspNet.Identity;

namespace EQueueVidly.Controllers
{
    public class TeachersController : BaseController
    {

        private UnitOfWork unitOfWork = new UnitOfWork(new ApplicationDbContext());

        //
        // GET: /Teachers/
        public ActionResult Index(int id)
        {
            var user = unitOfWork.Teachers.GetTeacherById(id).account;
            var model = new TeacherScheduleVM()
            {
                TeacherName = user.FirstName + " "+user.LastName,
                TeacherId = id,
                AccountId = user.Id
            };
            return View(model);
        }

       /* public IEnumerable<ApplicationUser> GetTeacherById(string id)
        {
            return from role in _context.Roles
                   where role.Name == "Teacher"
                   from userRoles in role.Users
                   join user in _context.Users
                   on userRoles.UserId equals id
                   select user;
        }*/
        
    }
}

EQueueVidly/Views/Teachers/Index.cshtml
\@using Microsoft.AspNet.Identity
@model EQueueVidly.ViewModels.TeacherScheduleVM

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* Teacher/Index/Id*@
<h1></h1>

<div class="row">
    <div class="panel panel-success">
        <div class="panel-heading">
            <div class="row flex-override">
                <div style="padding-left: 15px">
                    <img class=" img-circle img-responsive"
                     src="@Url.Action("Photo", "Account", new {UserId = Model.AccountId})" style="padding: 3px auto" width="50px" height="50px" />
                </div>
                <div class="col-md-5 vertical-align-center">
                    <div class=" valign-center">
                        <h2 class="panel-title">@Model.TeacherName</h2>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="panel-body">
            <div id='calendar'>

            </div>
        </div>
    </div>

</div>

  

<div id="JoinModal" class="modal" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="myModalLabel">Appointment</h3>
                </div>
                <div class="modal-body">
                    <dl class="dl-horizontal">
                        <dt>Appointment title:</dt><dd id="title"></dd>
                        <dt>Beginning:</dt><dd id="start"></dd>
                        <dt>Finish:</dt><dd id="end"></dd>
                        <dt>Time limit</dt><dd id="limit"></dd>
                        <dt>Total capacity:</dt><dd id="capacity"></dd>
                        <dt>Items in queue:</dt><dd id="queueItems"></dd>
                    </dl>
                </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="button" id="btnPopupCancel" data-dismiss="modal" class="btn">Cancel</button>
                    <button type="button" id="btnPopupJoin" data-dismiss="modal" class="btn btn-primary">Join</button>
                </div>
            </div>

        </div>

    </div>

@section scripts
{
    <script>
        var isTeacher = false;
        @if (User.IsInRole("Teacher"))
        {
            @:isTeacher = true;
        }
        var selectedEvent, isMember;
        var userId = '@User.Identity.GetUserId()';

        function getFormattedDate(date) { // get date in needed format
            var today = new Date(date);
            var dd = today.getDate();
            var mm = today.getMonth(); //January is 0!
            var hh = today.getHours();
            var min = today.getMinutes();
            if (hh == 0)
                hh = '00';
            if (min == 0)
                min = '00';
            var yyyy = today.getFullYear();
            if (dd < 10) {
                dd = '0' + dd
            }

            var month = new Array();
            month[0] = "Jan";
            month[1] = "Feb";
            month[2] = "Mar";
            month[3] = "Apr";
            month[4] = "May";
            month[5] = "Jun";
            month[6] = "Jul";
            month[7] = "Aug";
            month[8] = "Sep";
            month[9] = "Oct";
            month[10] = "Nov";
            month[11] = "Dec";

            var today = dd + '/' + month[mm] + '/' + yyyy + ' ' + hh + ':' + min;
            return today;
        }

        function IsMember(event) { // check if current user is already joined to the appointment
            if (!isTeacher) {
                var dataRow = { 'userId': userId, 'eventId': event.id };
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("IsAppointmentMember", "Attendees")',
                    data: dataRow,
                    success: function (response) {
                        if (response == 'True') {
                            isMember = true;
                        } else {
                            isMember = false;
                        }
                    }
                });
            } 
        }

        function IsFull(event) { // check wether appointment full or not
            return (event.queueIiems == event.capacity);
        }

        $('#btnPopupJoin').click(function() {
            var dataRow = {
                'AppointmentId': selectedEvent.id
            }
            if (isMember) {
                $("#calendar").fullCalendar('renderEvent', selectedEvent, true);
                $('#calendar').fullCalendar('refetchEvents');
                toastr.error("You cant join twice!");
            } else {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("JoinEvent", "Attendees")',
                    dataType: "json",
                    contentType: "application/json",
                    data: dataRow,
                    success: function (response) {
                        if (response) {
                            $("#calendar").fullCalendar('renderEvent', selectedEvent, true);
                            $('#calendar').fullCalendar('refetchEvents');
                            toastr.success('You successfully joined to this appointment!');
                        } else {
                            toastr.error("Some error accured!!");
                        }
                    }
                });
            }


        });

        $(document).ready(function() {

            $('#calendar').fullCalendar({
                header: {
                    left: 'today prev,next ',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultView: 'month',
                editable: false,
                allDaySlot: false,
                selectable: true,
                slotMinutes: 15,
                timezone: 'local',
                events: '@Url.Action("GetAppointmentsForTeacher", "Appointments", new {Id = Model.TeacherId})',
                eventClick: function(calEvent, jsEvent, view) {
                    selectedEvent = calEvent;
                    isMember = IsMember(calEvent);
                    var evenetStart = new Date(calEvent.start);
                    evenetStart = evenetStart.getTime();
                    var now = new Date().getTime();
                    if ((!userId) || (evenetStart <= now) || IsFull(calEvent) || isTeacher) {
                        $('#modal-footer').hide();
                    } else {
                        $('#modal-footer').show();
                    }

                    $('#JoinModal').modal();
                    $('#title')[0].innerHTML = calEvent.title;
                    $("#start")[0].innerHTML = getFormattedDate(calEvent.start);
                    $("#end")[0].innerHTML = getFormattedDate(calEvent.end);
                    $("#limit")[0].innerHTML = calEvent.timeLimit;
                    $("#capacity")[0].innerHTML = calEvent.capacity;
                    $("#queueItems")[0].innerHTML = calEvent.queueIiems;


                },
                eventRender: function (event, element) {

                },
            });
        });
    </script>
}

EQueueVidly/Views/Teachers/TeacherInfoPartial.cshtml
@using Microsoft.AspNet.Identity
@model EQueueVidly.ViewModels.IndexViewModel


<div class="panel panel-success">
    <div class="panel-heading" style="position: relative;">
        <h3 class="panel-title">@Model.FirstName @Model.LastName</h3>
    </div>
    <div class="panel-body">
        <div class="row" style="position: relative;">
            <img style="position: relative; bottom: 20px;" src="@Url.Action("Photo", "Account" , new { UserId=User.Identity.GetUserId() })" height="400" width="400" alt=" " class=" img-thumbnail img-responsive" />
        </div>

        <div class="row" style="padding: 10px;">
            <p style="margin-bottom: 5px"> <span style="padding-left: 7px; padding-right: 7px"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>@Model.Email</p>
            <p style="margin-bottom: 5px"> <span style="padding-left: 7px; padding-right: 7px"><i class="fa fa-phone fa" aria-hidden="true"></i></span>@Model.Phone</p>
            
        </div>

    </div>
</div>

 