EQueueVidly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EQueueVidly.Domain;
using EQueueVidly.Models;
using Glimpse.AspNet.Tab;
using PagedList;

namespace EQueueVidly.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork(new ApplicationDbContext());
        public ActionResult Index(string searchString, int page = 1)
        {
            int pageSize = 6;
            var teachers = unitOfWork.Teachers.GetAllTeachersWithAccount();

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = unitOfWork.Teachers.Find(p => 
                    (
                    p.account.FirstName.ToLower().Contains(searchString) || 
                    p.account.LastName.ToLower().Contains(searchString)
                    )).OrderBy(t=>t.AccountId);
            }


            return Request.IsAjaxRequest()
                ? (ActionResult)PartialView("TeacherList", teachers.ToPagedList(page, pageSize))
                : View(teachers.ToPagedList(page, pageSize));
        }

    }
}

EQueueVidly/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using EQueueVidly.Domain;
using EQueueVidly.Models;
using EQueueVidly.ViewModels;
using Microsoft.AspNet.Identity;

namespace EQueueVidly.Controllers
{
    public class TeachersController : BaseController
    {

        private UnitOfWork unitOfWork = new UnitOfWork(new ApplicationDbContext());

        //
        // GET: /Teachers/
        public ActionResult Index(int id)
        {
            var user = unitOfWork.Teachers.GetTeacherById(id).account;
            var model = new TeacherScheduleVM()
            {
                TeacherName = user.FirstName + " "+user.LastName,
                TeacherId = id,
                AccountId = user.Id
            };
            return View(model);
        }

       /* public IEnumerable<ApplicationUser> GetTeacherById(string id)
        {
            return from role in _context.Roles
                   where role.Name == "Teacher"
                   from userRoles in role.Users
                   join user in _context.Users
                   on userRoles.UserId equals id
                   select user;
        }*/
        
    }
}

EQueueVidly/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
@section Scripts {
    @Scripts.Render("~/bundles/app")
}

<div class="row">
    <div class="col-sm-4">
        <form data-bind="submit: callApi">
            <h3>Invoke API</h3>
            <div class="form-group">
                <label>User</label>
                <input class="form-control" type="text" readonly data-bind="value: user" />
            </div>
            <div class="form-group">
                <label>Result</label>
                <input class="form-control" type="text" readonly data-bind="value: result" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Call API</button>
            </div>
            <div class="form-group error-messages" data-bind="foreach: errors">
                <p data-bind="text: $data" />
            </div>
        </form>
    </div>

    <div class="col-sm-4">
        <form data-bind="submit: register">
            <h3>Register</h3>
            <div class="form-group">
                <label>FirstName</label>
                <input class="form-control" type="text" data-bind="value: registerFirstName" />
            </div>
            <div class="form-group">
                <label>LastName</label>
                <input class="form-control" type="text" data-bind="value: registerLastName" />
            </div>
            <div class="form-group">
                <label>Email</label>
                <input class="form-control" type="text" data-bind="value: registerEmail" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input class="form-control" type="password" data-bind="value: registerPassword" />
            </div>
            <div class="form-group">
                <label>Confirm Password</label>
                <input class="form-control" type="password" data-bind="value: registerPassword2"/>
            </div>

            <div class="form-group">
                <label>Phone</label>
                <input class="form-control" type="text" data-bind="value: registerPhone" />
            </div>

           
            <div class="form-group">
                <button type="submit" class="btn btn-default">Register</button>
            </div>
        </form>
    </div>

    <div class="col-sm-4">
        <h3>Log In</h3>
        <form data-bind="submit: login">
            <div class="form-group">
                <label>Email</label>
                <input class="form-control" type="text" data-bind="value: loginEmail" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input class="form-control" type="password" data-bind="value: loginPassword" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Log In</button>
                <button data-bind="click: logout" class="btn btn-default">Log Out</button>
            </div>
        </form>
    </div>
</div>

EQueueVidly/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EQueueVidly/Views/Home/Index.cshtml
@using EQueueVidly.Models
@using EQueueVidly.Helpers
@model PagedList.IPagedList<Teacher>
@{
    ViewBag.Title = "Home Page";
}

@section styles{
    <link rel="Stylesheet" href="@Href("~/Content/custom/teachers-grid.css")" />
}

@*Header*@
<div class="row">
    <div class="col-lg-12 page-header ">
        <div class="col-lg-6">
            <h1 class="dark-text" style="margin-top: inherit;">
                Our Teachers
            </h1>
        </div>
        <div class="col-lg-4 pull-right">
            <div class="bs-component"></div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" placeholder="Teacher name" id="SearchString" name="SearchString">
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="button" id="btnSearch">search</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" id="teachers-container">
    @Html.Partial("TeacherList", Model)

</div>




@section scripts
{

    <script>
        // Adding popstate event listener to handle browser back button
        window.addEventListener("popstate", function (e) {
            $.ajax({
                url: location.href,
                success: function (result) {
                    $('#teachers-container').html(result);
                }
            });
        });

        function ChangeUrl(page, url) {
            if (typeof (history.pushState) != "undefined") {
                var obj = { Page: page, Url: url };
                history.pushState(null, obj.Page, obj.Url);
            } else {
                alert("Browser does not support HTML5.");
            }
        }

        function getUrlVars() {
            var vars = [], hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for (var i = 0; i < hashes.length; i++) {
                hash = hashes[i].split('=');
                vars.push(hash[0]);
                vars[hash[0]] = hash[1];
            }
            return vars;
        }

        function search() {
            $.ajax({
                url: "@Url.Action("Index","Home")" + "Home/Index?searchString=" + $('#SearchString').val(),
                success: function (result) {
                    ChangeUrl("index", "@Url.Action("Index","Home")" + "Home/Index?searchString=" + $('#SearchString').val());
                    $('#teachers-container').html(result);
                }
            });
        }

        $(function () {
            $("#btnSearch").click(function () {
                search();
            });

            $("#SearchString").keypress(function (e) {
                if (e.keyCode == 13) {
                    search();
                }
            });
            $('body').on('click', '#teachers-container .pagination a', function (event) {
                event.preventDefault();
                console.log('page');
                var searchString = $('#SearchString').val();
                if (searchString == undefined || searchString == '') {
                    searchString = '';
                } else {
                    searchString = '&searchString=' + searchString;
                }
                var url = $(this).attr('href') + searchString;
                console.log(url);
                $.ajax({
                    url: url,
                    success: function (result) {
                        ChangeUrl('index', url);
                        $('#teachers-container').html(result);
                    }
                });
            });

        });

        $(document).ready(function() {
            var teachers = $("#teachers").DataTable({
                ajax: {
                    url: "/EQueueVidly/api/teachers",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "firstName",
                        render: function(data, type, teacher) {
                            return "<a href='@Url.Action("Index","Teachers")/index/" + teacher.teacherId + "'>" + teacher.firstName + " " + teacher.lastName + "</a>";/**/
                            
                        }
                    }
                ]
            });
        });
    </script>
}

EQueueVidly/Views/Home/TeacherList.cshtml
@using System.Security.Policy
@using Microsoft.AspNet.Identity
@using PagedList.Mvc
@model  PagedList.IPagedList<EQueueVidly.Models.Teacher>
<div class="row " >
    @foreach (var item in Model)
    {
        <div class="col-lg-4 col-sm-6 text-center">
            <a href="@Url.Action("Index", "Teachers", new {id = item.Id})">
                <img onerror="this.src='@Url.Content("~/Content/images/profile/placeholder-user.png")'" class="img-circle" style="margin: 0 auto;" src="@Url.Action("Photo", "Account", new {UserId = item.account.Id})" height="200" width="200" alt="" />
            </a>
            <a href="@Url.Action("Index","Teachers", new{id=item.Id})">
                <h5 class="teacher-grid red-border-bottom">
                    @item.account.FirstName @item.account.LastName
                </h5>
            </a>
                @*<small>Job Title</small>*@
        </div>
     }    
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))